<br /><br />
<div class="row">
    <div class="col-md-12">

        <?php
        if (isset($_REQUEST['error']) AND $_REQUEST['error'])
            echo "<br /><q style='color:red'>Unable to shorten that link. It is not a valid url.</q>";
        ?>

        <form action="/?action=addlinksubmitted" class="form-horizontal"  method="post">
            <div class="form-group">
                <div class="col-md-10">
                    <input type="text" class="form-control" id="link" name="link" placeholder="Shorten your link">
                </div>

                <div class="col-md-2">
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>