<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Bit.ly copy</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="./css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="./css/404.css" media="screen" rel="stylesheet" type="text/css">
</head>
<body>
<div class="container">
     <div class="row">
        <div class="col-md-12">
            <?= $this->content; ?>
        </div>
    </div>
</div>
</body>
</html>